### ISSUE TITLE
Browserify "Assigning to rvalue" problem.

### ISSUE THREAD

**Issue by pygy** [pygy/j2c#1]
https://gitter.im/pygy/j2c?at=557023b827d2203776cc8ee0

@quafzi said: 
> May I use j2c with browserify? Doing so results in error "Assigning to rvalue (175:6) while parsing …/node_modules/j2c/dist/j2c.commonjs.js"

https://github.com/pygy/j2c/blob/076e5df7abfc0aa4f2865e0f711a203abb9b541d/dist/j2c.commonjs.js#L175

Doesn't have any issue, however, and it works in NodeJS.

**Comment by barneycarroll** [comment]
Here's the stack from Browserify@10.2.3:

```sh
SyntaxError: Assigning to rvalue (175:6) while parsing C:\Users\Barney\Documents\git\boil\node_modules\j2c\dist\j2c.commonjs.js while parsing file: C:\Users\Barney\Documents\git\boil\node_modules\j2c\dist\j2c.commonjs.js
    at DestroyableTransform.end [as _flush] (C:\Users\Barney\Documents\git\boil\node_modules\browserify\node_modules\insert-module-globals\index.js:73:21)
    at DestroyableTransform.<anonymous> (C:\Users\Barney\Documents\git\boil\node_modules\browserify\node_modules\readable-stream\lib\_stream_transform.js:135:12)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:104:17)
    at prefinish (C:\Users\Barney\Documents\git\boil\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:450:12)
    at finishMaybe (C:\Users\Barney\Documents\git\boil\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:458:7)
    at endWritable (C:\Users\Barney\Documents\git\boil\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:469:3)
    at DestroyableTransform.Writable.end (C:\Users\Barney\Documents\git\boil\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:436:5)
    at DestroyableTransform.onend (C:\Users\Barney\Documents\git\boil\node_modules\browserify\node_modules\readable-stream\lib\_stream_readable.js:537:10)
    at DestroyableTransform.g (events.js:199:16)
```

**Comment by barneycarroll** [comment]
I can't work out how j2c@0.7.2 which I get from NPM is somehow completely different to what Github has for release 0.7.2, but in the NPM code lines 174-175 of `j2c.commonjs.js` are:

```javascript
      locals[k] || locals[k] = k+suffix;
      return match + suffix;
```

`Assigning to rvalue` sounds like it's struggling with parsing an assignment operation as part of a greater operation. Sure enough, this works without a hitch:

```javascript
      if( !locals[k] ) locals[k] = k+suffix;
      return match + suffix;
```

…so there probably is a Browserify AST problem in there somewhere. However, bearing in mind using Git to search this repo for `suffix` doesn't even yield any results, I tried mapping my dependency to the repo directly:

```json
{
  "dependencies": {
    "j2c": "git+ssh://git@github.com:pygy/j2c.git"
  }
}
```

And that works fine. In fact, even specifying the hash for the 0.7.2 release works fine.

So the fix would appear to be just to republish to NPM…

**Comment by pygy** [comment]
This code was part of the then `v0.8pre` now `next` branch, but I updated it to use `if` instead in the mean time

I guess I messed up the release, and ran `npm publish` from the wrong branch.

I'll push another release.

**Comment by pygy** [comment]
Done :-)

@barneycarroll thanks for the debugging :-)

**Comment by barneycarroll** [comment]
Weird — I mean, you really shouldn't have to change your internal code style to fit Browserify. ES6 should make this simpler because imports can only occur before any execution code, and exports must be top level, so it's all procedural. Browserify and other code that transpires CommonJS needs to be able to parse the whole AST to see if requires occur in deeper code etc, but still… weird!

**Comment by pygy** [comment]
A bug in their parser (operator precedence)...

**Comment by pygy** [comment]
@quafzi It should be fixed now (assuming you're still interested).
