### ISSUE TITLE
Babel complains about es6 build

### ISSUE THREAD

**Issue by ArthurClemens** [pygy/j2c#3]
When I try to compile with babel, I get
```
j2c.es6.js: undefined is not a function
    at PathHoister.run (/Users/arthur/code/mithril-infinite/mithril-infinite/node_modules/babel-plugin-closure-elimination/lib/index.js:135:48)
    at TraversalPath.enter (/Users/arthur/code/mithril-infinite/mithril-infinite/node_modules/babel-plugin-closure-elimination/lib/index.js:185:17)
    at TraversalPath.call (/Users/arthur/.node/lib/node_modules/babel/node_modules/babel-core/lib/babel/traversal/path/index.js:899:28)
    at TraversalPath.visit (/Users/arthur/.node/lib/node_modules/babel/node_modules/babel-core/lib/babel/traversal/path/index.js:931:10)
    at TraversalContext.visitMultiple (/Users/arthur/.node/lib/node_modules/babel/node_modules/babel-core/lib/babel/traversal/context.js:70:16)
    at TraversalContext.visit (/Users/arthur/.node/lib/node_modules/babel/node_modules/babel-core/lib/babel/traversal/context.js:100:19)
    at Function.traverse.node (/Users/arthur/.node/lib/node_modules/babel/node_modules/babel-core/lib/babel/traversal/index.js:64:17)
    at TraversalPath.visit (/Users/arthur/.node/lib/node_modules/babel/node_modules/babel-core/lib/babel/traversal/path/index.js:948:28)
    at TraversalContext.visitSingle (/Users/arthur/.node/lib/node_modules/babel/node_modules/babel-core/lib/babel/traversal/context.js:90:12)
    at TraversalContext.visit (/Users/arthur/.node/lib/node_modules/babel/node_modules/babel-core/lib/babel/traversal/context.js:102:19)
```

**Comment by pygy** [comment]
Thanks for the report, investigating...

**Comment by pygy** [comment]
It's working fine AFAICT...

```Bash
$ babel j2c.es6.js > out.js
$ node
> j2c = require("./out")
{ inline: [Function],
  sheet: [Function],
  scoped: [Function],
  prefix: [Function] }
>
```

How do you use Babel?

**Comment by ArthurClemens** [comment]
I was doing
```
babel j2c.es6.js --outfile j2c.js
```
but 
```
babel j2c.es6.js > j2c.js
```
gives the same result.

**Comment by pygy** [comment]
`babel-plugin-closure-elimination` may well be the culprit...

Investigating why.

**Comment by pygy** [comment]
Your trace matches https://github.com/codemix/babel-plugin-closure-elimination/issues/1.

Not sure why mine differs

**Comment by ArthurClemens** [comment]
I thought I only have this plugin in my local `.babelrc` file. Removing it does not help, perhaps there are other places where it is set.
Regardless, I don't have other problems with es6 code, so it must be a particular use of es6 code.

**Comment by pygy** [comment]
Yeah, j2c is wrapped in a IIFE that's inserted in various templates at build time. the closure elimination doesn't seem to like it.

Hopefully the folks at @codemix will fix it soon.

**Comment by pygy** [comment]
https://github.com/codemix/babel-plugin-closure-elimination/issues/1 should be fixed. @ArthurClemens does it work on your end?

**Comment by pygy** [comment]
Assuming it works. @ArthurClemens please re-open otherwise.
